create table task(
ID INT(11) not null AUTO_INCREMENT,
NAME VARCHAR(100) not null,
DESCRIPTION VARCHAR(4000),
DUE_DATE DATE not null,
USER_ID INT(11) not null,
PRIMARY KEY (ID),
FOREIGN KEY (USER_ID) REFERENCES user(ID) ON DELETE CASCADE
);