drop table user;
drop table task;

create table user(
ID INT(11) NOT NULL AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL DEFAULT 'unknown',
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(128) NOT NULL,
SALT VARCHAR(30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE KEY email_UNIQUE (EMAIL)
);
create table task(
ID INT(11) not null AUTO_INCREMENT,
NAME VARCHAR(100) not null,
DESCRIPTION VARCHAR(4000),
DUE_DATE DATE not null,
USER_ID INT(11) not null,
PRIMARY KEY (ID),
FOREIGN KEY (USER_ID) REFERENCES user(ID) ON DELETE CASCADE
);

insert into user(ID,NAME,EMAIL,PASSWORD,SALT) 
values(1,null,'root@localhost','4SOGKlM9jA0npAAl/hjjvXOCnF5vdoe3B0/71diSjimnABx9nvPrImyeKuMOBLeuN9X9k0O0ZSqaXuLcWq4s7A==','20ufjjJunk');
